name: EnderDrop
version: 'Alpha 0.1'
main: ch.hekates.enderdrop.Main
api-version: 1.19
description: A plugin to easily transfer Items between players.
author: Hekates

commands:
  enderdrop:
    aliases: ed
    permission: enderdrop.use
    usage: "Usage: /enderdrop [player]"

permissions:
  enderdrop.use:
    description: Allows you to use the /enderdrop command
    default: true